# Generated by Django 4.0.3 on 2022-03-13 03:15

from django.db import migrations
import isbn_field.fields
import isbn_field.validators


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='user',
        ),
        migrations.AddField(
            model_name='book',
            name='isbn',
            field=isbn_field.fields.ISBNField(default=0, max_length=28, validators=[isbn_field.validators.ISBNValidator], verbose_name='ISBN'),
            preserve_default=False,
        ),
    ]
