# Generated by Django 4.0.3 on 2022-03-28 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_book_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='sales',
        ),
    ]
