# Generated by Django 4.0.3 on 2022-03-13 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_alter_book_rating_alter_book_sales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='rating',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='book',
            name='sales',
            field=models.IntegerField(),
        ),
    ]
