# Generated by Django 4.0.3 on 2022-04-12 03:58

from django.db import migrations
import isbn_field.fields
import isbn_field.validators


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_genre_remove_book_genre_book_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=isbn_field.fields.ISBNField(blank=True, max_length=28, validators=[isbn_field.validators.ISBNValidator], verbose_name='ISBN'),
        ),
    ]
