# Generated by Django 4.0.3 on 2022-04-12 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0012_genre_remove_book_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
