# Generated by Django 4.0.3 on 2022-04-13 17:16

from django.db import migrations
import isbn_field.fields
import isbn_field.validators
import rating.models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='ISBN',
            field=isbn_field.fields.ISBNField(max_length=13, validators=[isbn_field.validators.ISBNValidator], verbose_name='ISBN'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='ratingnum',
            field=rating.models.MinMaxFloat(),
        ),
    ]
