# Generated by Django 4.0.3 on 2022-04-13 18:49

from django.db import migrations
import rating.models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0002_alter_rating_isbn_alter_rating_ratingnum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='ratingnum',
            field=rating.models.MinMaxFloat(max_length=1),
        ),
    ]
