# Generated by Django 4.0.3 on 2022-04-06 03:36

from django.db import migrations, models
import isbn_field.fields
import isbn_field.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('title', models.CharField(max_length=150)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('sales', models.IntegerField(blank=True, null=True)),
                ('isbn', isbn_field.fields.ISBNField(max_length=28, validators=[isbn_field.validators.ISBNValidator], verbose_name='ISBN')),
                ('idd', models.IntegerField(primary_key=True, serialize=False)),
                ('genre', models.ManyToManyField(related_name='books', to='books.genre')),
            ],
        ),
    ]
