# Generated by Django 4.0.3 on 2022-03-13 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_remove_book_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name': 'title'},
        ),
    ]
