# Generated by Django 4.0.3 on 2022-03-28 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_remove_book_sales'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='sales',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
