# Generated by Django 4.0.3 on 2022-03-28 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_book_sales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='sales',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
