# Generated by Django 4.0.3 on 2022-03-13 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_book_genre_book_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='sales',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='rating',
            field=models.CharField(max_length=50),
        ),
    ]
