# Generated by Django 4.0.3 on 2022-03-13 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_book_sales_alter_book_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='rating',
            field=models.FloatField(max_length=50),
        ),
        migrations.AlterField(
            model_name='book',
            name='sales',
            field=models.IntegerField(max_length=50),
        ),
    ]
